### ISSUE TITLE
Can this be used to make a plugin for lua

### ISSUE THREAD

**Issue by ChuufMaster** [Crashdummyy/roslynLanguageServer#2]
Exactly what the title says but I want to integrate it into [seblj/roslyn.nvim](https://github.com/seblj/roslyn.nvim) so that there isn't any reliance on mason because it doesn't look its going to be merged. 

I mostly want to ask if I can use this repository as reference for how to get the versions and stuff like that?

**Comment by ChuufMaster** [comment]
I also wan't to download it directly from the Microsoft feed instead of making releases

**Comment by ChuufMaster** [comment]
Actually I have figured out a way to get the version and compare it with the local one using only the azure API's which also gives me the url to download the zip from so I have actually figured it out but help is always welcome.

**Comment by Crashdummyy** [comment]
> Actually I have figured out a way to get the version and compare it with the local one using only the azure API's which also gives me the url to download the zip from so I have actually figured it out but help is always welcome.

So the download does work ?
That's cool.
When I implemented this I could only use the rest API to get the version but the download URL always ran into an 401.

If you check the issues at roslyn.nvim you'll see that I already asked for the need of a built-in updater. Maybe it can be done in the future as it really doesn't look like it will get merged into mason.

To circumvent this you can fork your own mason-registry like I do

**Comment by ChuufMaster** [comment]
> > Actually I have figured out a way to get the version and compare it with the local one using only the azure API's which also gives me the url to download the zip from so I have actually figured it out but help is always welcome.
> 
> 
> 
> So the download does work ?
> 
> That's cool.
> 
> When I implemented this I could only use the rest API to get the version but the download URL always ran into an 401.
> 
> 
> 
> If you check the issues at roslyn.nvim you'll see that I already asked for the need of a built-in updater. Maybe it can be done in the future as it really doesn't look like it will get merged into mason.
> 
> 
> 
> To circumvent this you can fork your own mason-registry like I do

I've actually finished the code that's needed to download it from roslyn.nvim itself skipping over mason completely. The only dependency is curl of course I've just gotta clean up some stuff and make a pull request and figure out how to integrate it with roslyn.nvim in a clean way. 

I'll push the stuff that I've done to my for of Roslyn.nvim later today if you wanna take a look. 

The problem with the downloading from the feed is that at some point you can't use the feed name you have to use the feed id.

**Comment by ChuufMaster** [comment]
@Crashdummy I have just pushed the mostly functional updates to the plugin I still want to refactor it quite a bit before making a PR into roslyn.nvim but it is working mostly atleast as far as I can tell

**Comment by Crashdummyy** [comment]
I'll close this issue for now.
We might be using [the dotnet tool](https://www.nuget.org/packages/roslyn-language-server) in the future but for now its missing blazor support.
Besides it is not receiving updates since they dropped it

**Comment by Crashdummyy** [comment]
I'll close this now.
There's now still roslyn.nvim and mason with lspconfig is working as well (still missing a few things tho).
